### ISSUE TITLE
Playlist download is not surpported now?

### ISSUE THREAD

**Issue by archtaurus** [marcopeocchi/yt-dlp-web-ui#10]
Playlist download is powerful, may everyone needs it :)

**Comment by marcopeocchi** [comment]
It's really a nice feature to have. Thanks for the advice!

Once I'll have a little spare time I'll implmement it.

**Comment by Zaedus** [comment]
Not exactly sure where you're at in development since this feature was requests, but I would also like to see this feature implemented! I am willing to work on a PR if this isn't worth the effort atm

**Comment by marcopeocchi** [comment]
@Zaedus @archtaurus I'm working on a download queue which will enable playlists downloading.

**Comment by CrazyWolf13** [comment]
> @Zaedus @archtaurus I'm working on a download queue which will enable playlists downloading. 😎

Hi thank you for creating this awesome web-ui, may I ask about the current state of the playlist support?
