### ISSUE TITLE
double extension on playlist and playlist variable not working

### ISSUE THREAD

**Issue by CrazyWolf13** [marcopeocchi/yt-dlp-web-ui#105]
Hi
You did an insanely great job with the template, I absolutely love it!

But currently I can see two things not working, 

Double fileextension: 
![image](https://github.com/marcopeocchi/yt-dlp-web-ui/assets/96661824/eef4044c-0afc-4977-a59b-401ad3c5ef91)
Each downloaded track shows once the original and then the transcoded filename.

Using Playlist_name in filename does not seem no work, they end up in "NA" Folder

Here is my template used together with playlists:
![image](https://github.com/marcopeocchi/yt-dlp-web-ui/assets/96661824/2ba872dc-c58f-4cff-89ff-0ed0d07a2ac5)

Huge thanks for looking into this!

**Comment by marcopeocchi** [comment]
hello @CrazyWolf13,

I've tested your template and everything works as intended now.
Tell me if there's anything else. 😎
