### ISSUE TITLE
Rights to delete

### ISSUE THREAD

**Issue by Spp595** [marcopeocchi/yt-dlp-web-ui#11]
I installed this container on a raspberry pi and created an smb storage to access the video using my PC, but I ran into a problem, I can't delete the videos buzzed through the container because of access rights. How can this be changed?

**Comment by marcopeocchi** [comment]
Hi @Spp595,
First of all there are things to consider. Your smb share has write permission? What mask is applied to the share folder? 
I'd suggest to mount the share folder with :rw option.

```
-v <your dir>:/usr/src/yt-dlp-webui/downloads:rw
```

**Comment by MarcusRiemer** [comment]
Maybe this is because the files on the host system have `root` as user on many systems where docker runs as `root`?

**Comment by Spp595** [comment]
> Maybe this is because the files on the host system have `root` as user on many systems where docker runs as `root`?
I have already solved this problem, just made a regular user the owner of the directory
