### ISSUE TITLE
Reverse proxy support broken for subdomains

### ISSUE THREAD

**Issue by AdamantUnstable** [marcopeocchi/yt-dlp-web-ui#114]
Steps to reproduce:
1) Host ytdlp-web-ui behind a reverse proxy using a subdomain rather than a sub path (eg ytdlp.home.lan or equivalent)
2) Load the web UI - get "An error has occurred" with a link to settings
3) Go to settings - the defaults are already correct with the correct subdomain and reverse proxy flag, so there's no settings to fix
4) It still doesn't work - attempting to go back to the main page just loads forever, refreshing goes back to the error page

Edit: this behaviour applies to the latest branch, on the master branch it just loads forever without even reaching the first error page

**Comment by Baipyrus** [comment]
Just set up for the first time, works perfectly for me. I use Nginx Proxy Manager and even run Authelia before reaching the WebUI.

**Comment by marcopeocchi** [comment]
@AdamantUnstable I'm encountering the same problem when authentication is enabled.
With `--auth` removed everything works. 
Does nginx automatically pass cookies when configured as reverse proxy?

![image](https://github.com/marcopeocchi/yt-dlp-web-ui/assets/35533749/86cdb18b-e728-403d-8c1e-152bf07eb0bc)

**Comment by marcopeocchi** [comment]
A possible soultion could be set the jwt in local storage

**Comment by marcopeocchi** [comment]
## Update

Now authentication uses headers instead of cookies and jwt is saved in localstorage.
Should improve reverse proxy compability.
