### ISSUE TITLE
Download Button

### ISSUE THREAD

**Issue by Baipyrus** [marcopeocchi/yt-dlp-web-ui#115]
Hi there,

found the project just today and much prefer it over an older [variant](https://github.com/timendum/Youtube-dl-WebUI) I've been using that just recently broke.

I'm kind of missing one feature here though, and that is a way to download from the Web-UI itself. Would love for a simple and quick feature like adding a button next to the media in archive or even the history/dashboard! The best place for it would truly only be in the archive though, where you could also give the item selection a secondary purpose besides deletion: bulk download.

Thanks in advance and keep up the good work!

**Comment by marcopeocchi** [comment]
Hello @Baipyrus,

It's a nice addition and easy to implement, I've scheduled it after #114.

**Comment by marcopeocchi** [comment]
File download is implemented atm, bulk download needs some work.

**Comment by Baipyrus** [comment]
Deleting entries in the archive is the exact opposite of the current state for downloading, weirdly enough. Would appreciate individual buttons. Thanks!

**Comment by marcopeocchi** [comment]
Bulk download feature has been added in the Home speed dial
![image](https://github.com/marcopeocchi/yt-dlp-web-ui/assets/35533749/1e949e68-263d-463f-8c73-15a718d3b688)

Download and view file has been respectively added for each download entry in the home dashboard
![image](https://github.com/marcopeocchi/yt-dlp-web-ui/assets/35533749/a442437b-2c2e-48a7-bf07-213999896d38)
![image](https://github.com/marcopeocchi/yt-dlp-web-ui/assets/35533749/09c61120-ecfa-44df-a74a-8a86fcf037ff)
