### ISSUE TITLE
Empty Archive

### ISSUE THREAD

**Issue by Baipyrus** [marcopeocchi/yt-dlp-web-ui#116]
Hi there,

found the project just today and much prefer it over an older [variant](https://github.com/timendum/Youtube-dl-WebUI) I've been using that just recently broke.

I just freshly installed the Software on a clean VM using the [Docker installation instructions](https://hub.docker.com/r/marcobaobao/yt-dlp-webui). I now sit here with an empty Archive, and when I click on it (also after deleting all previous downloads to clear archive), I sit in an infinite loading screen. Any ideas why this happens?

Thanks in advance and keep up the good work!

**Comment by marcopeocchi** [comment]
Hi @Baipyrus,

The DockerHub page is surely outdated, I've just updated it. Try to reinstall following the new **readme**'s steps.
If it still doesn't work, please provide the steps in order to replicate your setup. 

Let me know if there's anything else.

**Comment by marcopeocchi** [comment]
fixed in #114
