### ISSUE TITLE
Download to Subfolder?

### ISSUE THREAD

**Issue by MarcusRiemer** [marcopeocchi/yt-dlp-web-ui#12]
I roughly organize videos per show and have one folder per show. Currently your UI always downloads to the root folder and I move the file some time later manually. Would it be possible to enumerate all existing folders in the download directory (maybe in a simple `<select>`) and use that path as target path?

And thanks for this awesome GUI, I love having a possibility to very quickly add a new video to the kids library without firing up a SSH session.

**Comment by marcopeocchi** [comment]
![image](https://user-images.githubusercontent.com/35533749/192088580-dfa8865f-a3db-4dc2-9953-8d9276c4ecf7.png)

Hello @MarcusRiemer!

I think a `<select>` of the flattened tree of the _x_ folder could do the job. Above there's my proposal.

**Comment by MarcusRiemer** [comment]
That would be absolutely perfect 🤩

**Comment by marcopeocchi** [comment]
Pull request #13 approved, download path selection is now integrated.
