### ISSUE TITLE
Audio extraction

### ISSUE THREAD

**Issue by Baipyrus** [marcopeocchi/yt-dlp-web-ui#125]
Hello again,

after a nice and comfortable time using this software, I would like to submit a few suggestions on changes/additions:

For the very same reason as in #124, I would appreciate an extra option to extract audio in the "New download" menu for quick and easy access. Specific cases like manually downloading both Videos and Audios in an unordered/-listed way, make it clear that going to the settings twice (to enable and then later disable extraction) is rather irritating.

Thanks in advance and keep up the good work!

**Comment by marcopeocchi** [comment]
![Screenshot 2024-01-08 alle 13 22 02](https://github.com/marcopeocchi/yt-dlp-web-ui/assets/35533749/868dac00-3a77-4a05-85a1-b87b53cc4bea)

hello @Baipyrus!

Yes, it's better like this.

In conjunction with the revamped dropdown for the templates, it's much much better. (also corrected #124)
![Screenshot 2024-01-08 alle 12 36 39](https://github.com/marcopeocchi/yt-dlp-web-ui/assets/35533749/60ae9c7c-5477-40c4-89c9-fff44b990922)

**Comment by OneCreek** [comment]
Here the templates in text form:
slow
-r 50K
medium
-r 250K
fast
-r 1024K
group by uploader
-o %(uploader)s_%(channel_id)s/%(title)s.%(ext)s
mp3
-o '(playlist_title)s/%(title)s.%(ext)s' --extract-audio --audio-format mp3
subtitles
--write-sub
