### ISSUE TITLE
Host and port set in config file are not respected

### ISSUE THREAD

**Issue by gilliginsisland** [marcopeocchi/yt-dlp-web-ui#129]
This line `server.RunBlocking(host, port, frontend, localDatabasePath)` in `main.go` is not reading the host and port from the config file, it should be changed to `server.RunBlocking(c.host, c.port, frontend, localDatabasePath)`. 

Also would be nice if `localDatabasePath` was added to the config file similar to how `session_file_path` and `log_path` are.

**Comment by marcopeocchi** [comment]
hello @gilliginsisland,

if you're using yt-dlp-webui with docker is normal behavior, just use Docker's NAT. If you're using without Docker then there's a problem that needs to be addressed.

About `localDatabasePath` it can be added without problems.

**Comment by gilliginsisland** [comment]
I'm not using docker, I am running the binary directly. When passing host and port via cli args it works fine, its just through the config file that it doesn't work.

**Comment by mihaigalos** [comment]
I'm experimenting with yt-dlp-web on k8s, and this indeed impeding me.
The reason is that I'm using Traefik to route traffic and would like to be able to specify the ws:// URL.

**Comment by marcopeocchi** [comment]
I've updated the config struct. 
Now, all command line flags populates the struct to be overridden by the config file (if present).

```go
type Config struct {
	LogPath           string `yaml:"log_path"`
	EnableFileLogging bool   `yaml:"enable_file_logging"`
	BaseURL           string `yaml:"base_url"`
	Host              string `yaml:"host"`
	Port              int    `yaml:"port"`
	DownloadPath      string `yaml:"downloadPath"`
	DownloaderPath    string `yaml:"downloaderPath"`
	RequireAuth       bool   `yaml:"require_auth"`
	Username          string `yaml:"username"`
	Password          string `yaml:"password"`
	QueueSize         int    `yaml:"queue_size"`
	LocalDatabasePath string `yaml:"local_database_path"`
	SessionFilePath   string `yaml:"session_file_path"`

	path              string // reserved

	UseOpenId          bool   `yaml:"use_openid"`
	OpenIdProviderURL  string `yaml:"openid_provider_url"`
	OpenIdClientId     string `yaml:"openid_client_id"`
	OpenIdClientSecret string `yaml:"openid_client_secret"`
	OpenIdRedirectURL  string `yaml:"openid_redirect_url"`
}
```

@mihaigalos, regarding `websocket: close 1005 (no status)` it is due to the fact that the websocket connection is established and immediately closed (it was a problem only present in dev mode due to react 18 re-render).

Regarding the hijacked connection: it's the `jsonrpc.ServeConn` handler that taps in the httpResponseWriter (not an error but annoying in the logs).
