### ISSUE TITLE
it stops download until i docker restart it

### ISSUE THREAD

**Issue by ShotoZhao** [marcopeocchi/yt-dlp-web-ui#131]
it stops download until i docker restart it

**Comment by pythonxy** [comment]
sometimes clicking the Logs button can be a workaround

**Comment by ShotoZhao** [comment]
> hi all, I need more context in order to reproduce the issue.

first problem: i uploaded a text file with some youtube video links, but it stopped download some minutes later. after i restarted the container,it continued download.
second: if there are too many links in the text file(such as 100 links), the computer memory will overflow.

**Comment by marcopeocchi** [comment]
ok, thank you!
I'll look into that
