### ISSUE TITLE
Permission Issue

### ISSUE THREAD

**Issue by CrazyWolf13** [marcopeocchi/yt-dlp-web-ui#134]
Hi
I have the problem, previously when downloading via yt-dlp without yt-dlp web ui I could manage files shared on a samba drive from a windows user logged in with pi (default raspberrypi user) and it's samba password and could delete overwrite and manage those files, however when downloading via yt-dlp web ui docker I do not have admin permissions.

Is that a configuration mistake inside docker? Or is this a yt-dlp web-ui issue?
Not really sure, thanks!

**Comment by marcopeocchi** [comment]
Hello!

It's probably a mistake on your side. Try setting the --user flag in docker cli with your uid:gid (or user option in docker compose) (and even though it shouldn't be necessary).
I know that samba has a `directory_mask` option, if is badly set it might be the cause.

**Comment by CrazyWolf13** [comment]
I see, thanks a lot!

**Comment by CrazyWolf13** [comment]
Got it working!

Had to tinker a lot with docker issues and Portainer UI was reporting error after error, but by adding pi to the docker group and getting the correct docker command to finally work, it works like a charm!

Please keep up this software, it's amazing ❤️👏
