### ISSUE TITLE
Please add favicon.ico

### ISSUE THREAD

**Issue by 0x6d61726b** [marcopeocchi/yt-dlp-web-ui#139]
To have an identifying favicon image in my Firefox bookmark toolbar, I have modified the "no active downloads" icon ![favicon](https://github.com/marcopeocchi/yt-dlp-web-ui/assets/25281946/0445e0f1-1b76-4dd2-8252-f84d52427312) and made the [favicon.ico.zip](https://github.com/marcopeocchi/yt-dlp-web-ui/files/14473521/favicon.zip) file ready to be served (github upload does not allow .ico files, so it is zipped).

I would be very happy if you could add it in the future to the application. For now, it gets served via nginx reverse proxy.

There would be two steps to do so, if I remember right:

1. Add `favicon.ico` file to HTML root directory (because Firefox automatically loads the favicon.ico file from this location)
2. Add `<link rel="icon" type="image/x-icon" href="favicon.ico">` entry to index.html header section.

Thanks,
Mark

**Comment by marcopeocchi** [comment]
Hello @0x6d61726b,

The icon looks fine :)
Surely better than nothing. I'll try to add it ASAP.

**Comment by marcopeocchi** [comment]
I see. In the main.go the public directory isn't embedded.

**Comment by marcopeocchi** [comment]
I moved the favicon to the `src/assets` folder so Rollup can bundle it correctly

**Comment by 0x6d61726b** [comment]
I did a new build and it works perfectly. Thanks a lot. :-)
