### ISSUE TITLE
ARM binary does not work on ARMv6 - illegal instruction

### ISSUE THREAD

**Issue by jacklul** [marcopeocchi/yt-dlp-web-ui#141]
Hello, is there a chance to include ARMv6 binary in the releases?

I noticed in the Makefile that GOARM is not being specified for the ARM builds ([go wiki recommends to use it](https://zchee.github.io/golang-wiki/GoArm/)) and doesn't seem to work on ARMv6 machine - illegal instruction error. 

I would like to suggest targeting individual ARM revisions separately:
```
CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=6 go build -o build/yt-dlp-webui_linux-armv6 main.go
CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=7 go build -o build/yt-dlp-webui_linux-armv7 main.go
```

Could also be for v5 but I doubt anyone uses those nowadays.

**Comment by marcopeocchi** [comment]
Hi @jacklul 

ARM version prior to ARMv7 had been deprecaded. I will reintroduce build for ARMv6 for the binary releases.

**Comment by jacklul** [comment]
I just tried your newest build and armv6 binary is still giving me Illegal instruction, I think you made a little mistake in Makefile and  generated armv6 binary as armv7 file and vice versa

**Comment by marcopeocchi** [comment]
You're right they're swapped
