### ISSUE TITLE
Download live stream issue

### ISSUE THREAD

**Issue by thuban-kr** [marcopeocchi/yt-dlp-web-ui#151]
Hi 
I really like your great project!

At some point, downloading live streams is not working, but videos that are not live streams will still download fine.
![yt_bug1](https://github.com/marcopeocchi/yt-dlp-web-ui/assets/102015837/717fe944-3cd8-41df-ae57-a3c908217145)

I tried to download manually inside the yt-dlp-webui container, and the log is here
![yt_bug2](https://github.com/marcopeocchi/yt-dlp-web-ui/assets/102015837/6529d3b3-4afa-4b7d-891f-95296c730599)

**Comment by marcopeocchi** [comment]
Hi @thuban-kr,

I think is something related to the base container. The ffmpeg build may have been built without gnutls.
For context, a standalone yt-dlp build is able to download that livestream?

**Comment by thuban-kr** [comment]
You were right. I checked with 'ffmpeg -protocols' and https wasn't among the supported protocols. 
The other yt-dlp container with alpine could download a livestream, so is there no other way but to wait?

**Comment by thuban-kr** [comment]
I didn't expect you to change the base image. 
It works perfectly. Thank you so much!
