### ISSUE TITLE
How to bulk clean the dashboard?

### ISSUE THREAD

**Issue by zzlatew** [marcopeocchi/yt-dlp-web-ui#156]
Hi, I want to fully clear my dashboard because I have so much downloaded videos and it takes more time to load the page. I can see that every downloaded video has a "clear button" but I can't click on "clear" on 1500+ videos. Thanks in advance.

**Comment by marcopeocchi** [comment]
Hello @zzlatew,

In the speed dial (bottom right button) there's a thrash bin icon that serves also as clearing completed downloads.

**Comment by zzlatew** [comment]
Thank you so much, I really appreciate your time! Take care!

**Comment by marcopeocchi** [comment]
> Hi, I want to fully clear my dashboard because I have so much downloaded videos and it takes more time to load the page. I can see that every downloaded video has a "clear button" but I can't click on "clear" on 1500+ videos. Thanks in advance.

in the latest builds (latest tag) the "table view" has been changed to handle thousands of videos without loading slowly.
Soon the "card view" will be also refactored like this.
