### ISSUE TITLE
Add support for Megatools?

### ISSUE THREAD

**Issue by cablehub** [marcopeocchi/yt-dlp-web-ui#158]
This is actually a great web UI, not a terrible one :)

Would you consider adding support for _Megatools_ (https://megatools.megous.com/)? Those work very similar to _yt-dlp_, just a single, statically linked executable.

Just the `megatools get` part, of course, not the whole shebang.

**Comment by marcopeocchi** [comment]
Hello @cablehub,

I'm planning this, but I feel like it's a little bit out of scope. Maybe an entirely separate project suits best.

**Comment by cablehub** [comment]
> I'm planning this, but I feel like it's a little bit out of scope. Maybe an entirely separate project suits best.

That would be awesome since there is no decent self-hosted web UI out there for Mega last time I checked.

Maybe you could fork and have two separate projects with a similar enough code base to minimize maintenance and further development.

Big thanks for taking this into consideration!
