### ISSUE TITLE
Can't download video in custom format

### ISSUE THREAD

**Issue by airosa-id** [marcopeocchi/yt-dlp-web-ui#163]
**Version running**
[v3.1.1](https://github.com/marcopeocchi/yt-dlp-web-ui/tree/v3.1.1)

**Describe the bug**
After selecting the video format and clicking the "Download" button, a popup window appears at the bottom with the message "requested" (just one word) and the download does not occur.

P.S. If you do not use the format selection function, the download works correctly at the highest possible quality.

**To Reproduce**
1. Go to '+'
2. Write URL
3. press select format
4. Choose any format
5. Press Download
6. Popup and its all

**Expected behavior**
Download Video file :)

**Screenshots**
![image](https://github.com/marcopeocchi/yt-dlp-web-ui/assets/10205470/7897462a-c051-4b47-8953-9ec5b07224f8)

**Additional context**
in log i see:
Jul 10 16:43:54 orangepi3-lts yt-dlp-webui[25753]: time=2024-07-10T16:43:54.199+03:00 level=ERROR msg="failed to init database" err="unable to open database file: out of memory (14)"
Jul 10 16:43:54 orangepi3-lts yt-dlp-webui[25753]: time=2024-07-10T16:43:54.201+03:00 level=INFO msg="yt-dlp-webui started" address=192.168.1.250:8100
Jul 10 16:43:54 orangepi3-lts yt-dlp-webui[25753]: time=2024-07-10T16:43:54.203+03:00 level=INFO msg="sucessfully persisted session"
Jul 10 16:45:05 orangepi3-lts yt-dlp-webui[25753]: 2024/07/10 16:45:05  Metadata   Formats  https://www.youtube.com/watch?v=iAzUWylcJCM
Jul 10 16:45:05 orangepi3-lts yt-dlp-webui[25753]: time=2024-07-10T16:45:05.597+03:00 level=INFO msg="retrieving metadata" caller=getFormats url="https://www.youtube.com/watch?v=iAzUWylcJCM"

**Comment by Anqui3tas** [comment]
I receive similar, appears to accept download, then does nothing. thought it was a permission error so added: 
Users: XXXX:XXX to my compose file, but that results in a "failed to persist" error. (but still launches and does the same thing)

<head></head>
date | stream | content
-- | -- | --
2024/07/12 09:27:10 | stdout | time=2024-07-12T16:27:10.483Z level=INFO msg="retrieving metadata" caller=getFormats url="https://www.youtube.com/watch?v=a25jGD2FUbY"
2024/07/12 09:27:10 | stderr | 2024/07/12 16:27:10 [1;41m Metadata [0m [1;44m Formats [0m https://www.youtube.com/watch?v=a25jGD2FUbY
2024/07/12 09:25:48 | stdout | time=2024-07-12T16:25:48.495Z level=INFO msg="retrieving metadata" caller=getFormats url="https://www.youtube.com/watch?v=a25jGD2FUbY"
2024/07/12 09:25:48 | stderr | 2024/07/12 16:25:48 [1;41m Metadata [0m [1;44m Formats [0m https://www.youtube.com/watch?v=a25jGD2FUbY
2024/07/12 09:25:21 | stdout | time=2024-07-12T16:25:21.096Z level=INFO msg="sucessfully persisted session"
2024/07/12 09:25:21 | stdout | time=2024-07-12T16:25:21.096Z level=INFO msg="yt-dlp-webui started" address=0.0.0.0:3033
2024/07/12 09:25:21 | stderr | 2024/07/12 16:25:21 [1;41m config [0m open /config/config.yml: no such file or directory

**Comment by GreyFlorence** [comment]
same issue here with lastest versions of yt-dlp and webui
