### ISSUE TITLE
[Feature Request] OpenID Authentification

### ISSUE THREAD

**Issue by CrazyWolf13** [marcopeocchi/yt-dlp-web-ui#169]
Hi
I recently found about OpenID standard, it's basically standartised login protocol, which allows login through all kinds of applications like for example authentik/authelia, supporting such a protocol would open an enourmous world, as with just that protocol, one can have authentification via github, google, pw+username, TOPT, ..... and many more through authentification management applications.

In my eyes that would also be a nice integration, as this project could focus less on implementing such login integrations and plugins and instead leave those to dedicated apps for security and login.

Authentik for example is also really easy to install, and has a nicely understandable UI.

Thanks for the amazing work!

**Comment by marcopeocchi** [comment]
Exciting stuff!

In this weekend I'll give it a shot and try to implement it 😄

**Comment by CrazyWolf13** [comment]
Wow, Awesome! 😎

**Comment by marcopeocchi** [comment]
A small defect:
![image](https://github.com/user-attachments/assets/7e4faee5-4a5f-4c37-b098-8f034088135d)
This will be the authentication page (even if OpenId is disabled the text field will be still present)

**Comment by CrazyWolf13** [comment]
Well that was quick :)

Looks awesome!!
Thankss!

If you have any questions about authentik, feel free to hit me on discord(In your server) or via matrix: @crazywolf13:matrix.org

**Comment by CrazyWolf13** [comment]
Any reason why there is an email field next to openid login Button?

Isn't that button supposed to take me to Google Auth or authentik where I then log in with email?

**Comment by marcopeocchi** [comment]
> Isn't that button supposed to take me to Google Auth or authentik where I then log in with email?

Yes, I will refactor it. There will no email text field before merging.

**Comment by CrazyWolf13** [comment]
@marcopeocchi  

Huge thanks, and how fast this was merged!!
