### ISSUE TITLE
Could you add the feature to use an external database server?

### ISSUE THREAD

**Issue by masukatto0281** [marcopeocchi/yt-dlp-web-ui#176]
Hello,
I found this great Web UI when managing my downloaded videos on yt-dlp.

One thing I am concerned about is the use of a local database (SQLite).
If this could use an external RDB server (e.g., PostgreSQL), it would be more resistant to data loss, etc., and more usable.

I am not too familiar with Golang, although I think just need to change one line here.
https://github.com/marcopeocchi/yt-dlp-web-ui/blob/16f8f74f9bf3a201444571f86415ba5aab4d0140/server/server.go#L83
As long as Connection settings, etc., I can be configurable in the config file (even if not in the UI).

Thank you.

**Comment by masukatto0281** [comment]
Oops, I was mistaken.
The database was not used to manage the history of downloaded videos, only the templates, right?

I thought I could see the list of downloaded videos in the web UI. If not, the database seems to be fine with the traditional SQLite.

**Comment by marcopeocchi** [comment]
You're right @masukatto0281 the sqlite database is only for templates.

Downloads' statuses are periodically serialized to a file.
The file is used only for download-resuming purposes.

**Comment by masukatto0281** [comment]
Thank you for your response.
I would like to have a UI where I can manage my downloaded files.

I would be happy to consider this as a future additional feature in this app.
