### ISSUE TITLE
Missing support for direct YT livestream DLs

### ISSUE THREAD

**Issue by emanueljg** [marcopeocchi/yt-dlp-web-ui#178]
**Version running**
```md
yt-dlp-web-ui: manually built current master
yt-dlp: v2024.08.06
```

**Describe the bug**
- `--live-from-start` works, but there's 0 logs or visual feedback of it downloading anything (I had to continuously `du` my destination directory to confirm it was doing anything) 
- `--wait-for-video` flat out doesn't work, and won't start downloading a stream even once it has begun

**To Reproduce**
`--live-from-start`:
Try to download any ongoing livestream with the template `--live-from-start`. 

`--wait-for-video`:
1. Choose a livestream that has not yet started
2. Start a download in the ui with the template `--live-from-start --wait-for-video 60` (check for livestream start each minute)
3. Have livestream start
4. Wait > 60 seconds
5. Check size of destination dir: should not increase, meaning no downloading is occuring 

See above

**Expected behavior**
`--live-from-start`:
Clear feedback from the service, both in logs and UI, that progress is being made
`--wait-for-video`:
Should start downloading once video has been detected.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by marcopeocchi** [comment]
It's a WIP. The [feat-livestream-support](https://github.com/marcopeocchi/yt-dlp-web-ui/tree/feat-livestream-support) branch was created to solve this issue.

**Comment by marcopeocchi** [comment]
It will look like something like this
![image](https://github.com/user-attachments/assets/702802e6-da5d-4ec0-b250-85a879f94950)

I need to test some edge cases before merge into master

**Comment by marcopeocchi** [comment]
Experimental support merged into master

**Comment by CrazyWolf13** [comment]
@marcopeocchi  That's awesome!

Would you consider anywhen in the future (low prio) adding support for twitch streams? for example via streamlink?

Thanks for you opinion on this, If that's something you like, I'd create a new issue and may be able to assist in the process.
