### ISSUE TITLE
add proxy option in setting tab 

### ISSUE THREAD

**Issue by keekychen** [marcopeocchi/yt-dlp-web-ui#18]
`yt-dlp` support parameter `--proxy URL`, but I found I am not able to set that in `yt-dlp-web-ui` 's setting tab.
could you add that function?

**Comment by marcopeocchi** [comment]
hi @keekychen,
sure proxy is a valid option to have. It will be included.

**Comment by marcopeocchi** [comment]
@keekychen with the last update you can pass arbitrary params to yt-dlp, including the `--proxy` one.
Enable the option to allow passing custom params/arguments in the settings page.
