### ISSUE TITLE
Latest 3.2.0 released binary is still the same old version file

### ISSUE THREAD

**Issue by GreyFlorence** [marcopeocchi/yt-dlp-web-ui#183]
Hi, just a reminder that the lastest released binary file in release page is still the same file of v3.1.2 rather than v3.2.0 :)

**Comment by marcopeocchi** [comment]
Probably has been built with the previous version frontend. My bad :D

**Comment by marcopeocchi** [comment]
Binaries updated!

**Comment by GreyFlorence** [comment]
> Binaries updated!

Thanks! It's working perfectly rn! Excited for the new livestream feature 😃!
