### ISSUE TITLE
Feature Request: saving cookies in the backend

### ISSUE THREAD

**Issue by GreyFlorence** [marcopeocchi/yt-dlp-web-ui#184]
Hi,so my IP was marked suspicious by YouTube so that cookies are required to download videos. 

My cookies work fine and stored in my PC browser. However in another browser or my phone, cookies are not stored, so that I have to put cookies all over again

Can you make cookies saved in the hosting server so that users don't have to re-input cookies for each of their other devices or browsers?

**Comment by marcopeocchi** [comment]
It would be a nice QoL improvement.
