### ISSUE TITLE
Wrong audio language

### ISSUE THREAD

**Issue by bonnebulle** [marcopeocchi/yt-dlp-web-ui#192]
**Version running**
RPC v3.2.0
yt-dlp v2024.08.06 

**Describe the bug**
Am downloading a video from Arte.tv
for example :
https://www.arte.tv/fr/videos/106655-000-A/les-parcs-nationaux-americains/
The formats I can download are "VF" (version FRench)
but, for this video, exists multiple audio tracks, not all in FRench !
( I test `yt-dlp --list-formats "https://www.arte.tv/fr/videos/106655-000-A/les-parcs-nationaux-americains/"` )  

**To Reproduce**
1. Go to 'Dashboard'
2. URL 'https://www.arte.tv/fr/videos/106655-000-A/les-parcs-nationaux-americains/'
3. Clic "Select Format"
4. Scroll down to choose an Audio Format
5. All are "FR"
6. clic first one for test
7. Download end
8. My video audio track is in Dutsh ;)

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/e2b78b92-dc10-40b8-9f2e-d5aa0a6aec54)

**Additional context**
I do a quick fix adding this arg
`--write-info-json -f 'bestvideo[height<=720]+VF-audio_0-Français'`
I have the right language... but not the right definition...
( but it is an other story )

Thanks
again

**Comment by marcopeocchi** [comment]
In order to list formats yt-dlp-webui uses `-J`.

If you run `yt-dlp -J "https://www.arte.tv/fr/videos/106655-000-A/les-parcs-nationaux-americains/" | jq` you can see that the `format_note` is always `"Français [VF]"` but the `"language" property changes.
```json
...
{
          "format_id": "VF-audio_0-Français__confort_audio_",
          "format_note": "Français [VF]",
          "format_index": null,
          "url": "https://arte-cmafhls.akamaized.net/am/cmaf/106000/106600/106655-000-A/20240724144377555166C6E0EEAEF5DA3D122D44B2/medias/106655-000-A_aud_VF-FRA_3_CA.m3u8",
          "manifest_url": "https://manifest-arte.akamaized.net/api/manifest/v1/Generate/20240724144377555166C6E0EEAEF5DA3D122D44B2/fr/XQ+KS/106655-000-A.m3u8",
          "language": "fr",
          "ext": "mp4",
          "protocol": "m3u8_native",
          "preference": null,
          "quality": null,
          "has_drm": false,
          "vcodec": "none",
          "language_preference": 110011,
          "resolution": "audio only",
          "aspect_ratio": null,
          "http_headers": {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "Accept-Language": "en-us,en;q=0.5",
            "Sec-Fetch-Mode": "navigate"
          },
          "audio_ext": "mp4",
          "video_ext": "none",
          "vbr": 0,
          "abr": null,
          "tbr": null,
          "format": "VF-audio_0-Français__confort_audio_ - audio only (Français [VF])"
        }
...
```

I've added the language property also to the response of the format selection so it will look like this 😄 

![image](https://github.com/user-attachments/assets/f1c0be5e-3eab-4b8b-ba8c-74208dfc1d4f)

**Comment by bonnebulle** [comment]
It is much better, very thank you for the quick fix, amazing !
(my non geek friends will be very graceful)

Sorry to re-open so shortly
Like in your example, in some cases, we have multiple "FR"
`yt-dlp --list-formats https://www.arte.tv/fr/videos/109848-000-A/sous-l-oeil-de-pekin-total-trust/`
=> 
```
ID                                         EXT RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC     MORE INFO
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
VF-STF-audio_0-Allemand                    mp4 audio only     │                  m3u8  │ audio only        unknown    [de] Français [VF]
VF-STF-audio_0-Français                    mp4 audio only     │                  m3u8  │ audio only        unknown    [fr] Français [VF]
VF-STF-audio_0-Français__audiodescription_ mp4 audio only     │                  m3u8  │ audio only        unknown    [fr] Français [VF]
```
==
![image](https://github.com/user-attachments/assets/98dc9504-53c6-4cac-9a9b-661c0a23e01f)

It should be possible to indicate the full "id" ?
EX/ `VF-STF-audio_0-Français__audiodescription_`
( in text button or tooltip/title maybe )
so, we dont have no more ambiguity !

Thanks again, this can be a extra modification,
the previous fix you done was already amazing !
have a nice day
