### ISSUE TITLE
Showing 401 when downloadPath is `./xxxxx`

### ISSUE THREAD

**Issue by eric2788** [marcopeocchi/yt-dlp-web-ui#195]
**Version running**
Provide the docker label or release tag you're running.

latest (`sha256-6de301f1c537a5378bdf732593995b056a5f4555a4df39a622047a4564cb0977.sig`)

**Describe the bug**

as title.

it it caused by this

```go
if strings.Contains(filepath.Dir(filename), root) {
		http.ServeFile(w, r, filename)
		return
	}

	w.WriteHeader(http.StatusUnauthorized)
```

when the downloadPath is `./downloads`, the filename will become `./downloads/abc.mp4`, but after `filepath.Dir(filename)` or `yt-dlpp print --filename`, it will become `/downloads` (which removed `.`), causing `strings.Contains("/downloads", "./downloads") == false` 

**To Reproduce**

1. config.yml: set the downloadPath to relative path ( `./xxxxxx` )
2. download a video/audio via web ui

**Expected behavior**

able to download or view via clicking button

**Screenshots**
![image](https://github.com/user-attachments/assets/85e4ac18-4b6e-4859-83ea-af93708c8fb8)

**Solution**

whether change to 

```go
if strings.Contains(filepath.Dir(filepath.Clean(filename)), filepath.Clean(root)) {
		http.ServeFile(w, r, filename)
		return
}
```

or 

tell user to use `foo/bar` instead of `./foo/bar` in config

**Comment by marcopeocchi** [comment]
Hello @eric2788,

I've updated the filename's guard as you suggested (using `filepath.Clean`). 
Testing the archive, download and view functionalities with a relative path behaves as expected.

If I'm missing something else, just reopen the issue.
