### ISSUE TITLE
session.dat will never restore if session_file_path is not `.`

### ISSUE THREAD

**Issue by eric2788** [marcopeocchi/yt-dlp-web-ui#202]
**Version running**
Provide the docker label or release tag you're running.

latest

**Describe the bug**

the `Restore` function doesn't contain `SessionFilePath`

![image](https://github.com/user-attachments/assets/763ceddf-1ce2-4ca6-936e-51b8f87e0dff)

**To Reproduce**
1. change `session_file_path` and restart
2. add a video/audio
3. restart server / recreate container

**Expected behavior**
downloads still there

**Screenshots**

**Additional context**

**Comment by marcopeocchi** [comment]
OMG, that's really dumb of me.
