### ISSUE TITLE
Feature Request: Data location for requesting client

### ISSUE THREAD

**Issue by gsmitheidw** [marcopeocchi/yt-dlp-web-ui#21]
It would be great if the following options could be available:

1. Download to requesting client directly. Could the downloaded data be redirected to the browser of the client and not download into the container/server at all? Not sure if this is possible without locally caching the file first? The use case I'm thinking of implementing another install for somebody else on their SBC that doesn't have much storage available. 

2. As a secondary option, when downloading to the default location on the container/server - could the list of downloads made be presented to the client with an option to download them or delete them? 

One workaround would be to present the downloads folder in Apache in the host - but a bit messy having two locations. Or maybe use rclone to sync changes to the client over scp etc.

**Comment by marcopeocchi** [comment]
The first option is doable, it requires a little bit of work. Caching the file is inevitable.

Second option it was planned long ago as a sort of "download archive".

To sum up, it is a nice addition and it will be introduced asap.
