### ISSUE TITLE
Some videos with too long titles cannot be downloaded because the Web UI lacks necessary setting items.

### ISSUE THREAD

**Issue by YamatoRyou** [marcopeocchi/yt-dlp-web-ui#22]
Example: `https://www.youtube.com/watch?v=dGYNinKfUR4`
The original yt-dlp can solve this problem by changing the file name when downloading with `-o`.

**Comment by marcopeocchi** [comment]
In the settings it will be available a new option to override the output filename [😎](https://emojipedia.org/smiling-face-with-sunglasses/)

![image](https://user-images.githubusercontent.com/35533749/211146795-24aec5c0-a7b8-4e9e-a161-f3aa01f284d2.png)
![image](https://user-images.githubusercontent.com/35533749/211146801-822b1513-9f3a-4933-ae19-51ff88c97f5d.png)

**Comment by marcopeocchi** [comment]
Fixed by #23
