### ISSUE TITLE
Enhancing yt-dlp-web-ui frontend

### ISSUE THREAD

**Issue by hfmanson** [marcopeocchi/yt-dlp-web-ui#230]
Hello,

I'd like to enhance the frontend of yt-dlp-web-ui by adding a youtube search facility using the google youtube data api.
Is it possible to have a yt-dlp-web-ui which uses a directory based frontend for development?

**Comment by marcopeocchi** [comment]
Hi @hfmanson,

Directory based template is a couple line of code tweak, so yes it will be done.

Regarding the YouTube search: I'm planning to rewrite the frontend with a new UI library. I'm planning this but I can't say you when it will be implemented.

**Comment by marcopeocchi** [comment]
Custom path based frontend can now be used.

Load the frontend's directory via the ``--web`` flag or via the config file.
Everything is in the readme in the **custom frontend** section.

**Comment by hfmanson** [comment]
awesome!
