### ISSUE TITLE
Docker mount point issue

### ISSUE THREAD

**Issue by charettemtb** [marcopeocchi/yt-dlp-web-ui#30]
Hi,
I'm using image recommended Docker image.
But download mount point should point to /downloads not /usr/src/yt-dlp-webui/downloads.
Am I right ?
Thanks

**Comment by marcopeocchi** [comment]
Hi @charettemtb,

My fault, I've changed the volume mounting point without updating the `README.md`.
It indeed point to `/downloads`

**Comment by charettemtb** [comment]
Thanks
