### ISSUE TITLE
Issue with docker : "permission denied: unknown"

### ISSUE THREAD

**Issue by charettemtb** [marcopeocchi/yt-dlp-web-ui#33]
Hi,
first of all thanks for your work.

I'm facing an issue with Docker compose:

> 
> Recreating ytdlp ... error
> 
> ERROR: for ytdlp  Cannot start service ytdlp: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/usr/bin/yt-dlp-webui": permission denied: unknown
> ERROR: Encountered errors while bringing up the project.

Seems this append with last build.
Could you help me ?
Thanks

**Comment by marcopeocchi** [comment]
Hi @charettemtb,
I'm having problems with Docker CI. I'm going to release a new version which hopefully fixes the problem. Just a matter of minutes.

**Comment by marcopeocchi** [comment]
A new image has been released both on docker hub and ghcr.io

**Comment by charettemtb** [comment]
Perfect, It works.
Thanks
