### ISSUE TITLE
No download start anymore

### ISSUE THREAD

**Issue by michelebossa** [marcopeocchi/yt-dlp-web-ui#36]
Hi,
I have a problem to download the youtube video at moment i'm getting for all video this message:
<img width="455" alt="image" src="https://user-images.githubusercontent.com/38975058/219877795-35be7856-8da1-4b52-891a-54b863d369e5.png">

Can i made something to fix?

Thanks.

**Comment by marcopeocchi** [comment]
Hi @michelebossa

It's a yt-dlp side issue fixed a couple of days ago.
Try the new image built last night.

**Comment by michelebossa** [comment]
it is not worked maybe it is a tag version issue i have set the latest in ghcr but i see an hold data on this version.
<img width="335" alt="image" src="https://user-images.githubusercontent.com/38975058/219879324-860ef5f2-5d27-49ef-8db8-4d6ad2775cc6.png">
 Can you check please?

**Comment by marcopeocchi** [comment]
try the master branch image
use :master

if it works I'll issue a new release

**Comment by michelebossa** [comment]
it is work i see the downloads started
<img width="848" alt="image" src="https://user-images.githubusercontent.com/38975058/219881497-c3be9760-ab0f-4716-93ff-22a50e5b684c.png">

**Comment by marcopeocchi** [comment]
Glad it works!
