### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Jmmx1237** [marcopeocchi/yt-dlp-web-ui#39]
Is there a way, to update the software?

**Comment by marcopeocchi** [comment]
Docker containers are stateless.
Unless you're using the single binary version, the only way to effectively update is update the image.

**Comment by Jmmx1237** [comment]
Thanks for your reply, I have now tried to start the current version via docker, however, no videos can be downloaded with it, an older version runs without problem.

docker run -d -p 3033:3033 -v /mnt/videos/:/downloads ghcr.io/marcopeocchi/yt-dlp-web-ui:latest

The server starts and can be reached, but the download does not start, even after waiting 1 hour. Maybe I am doing something wrong?

**Comment by marcopeocchi** [comment]
at the moment try the image `ghcr.io/marcopeocchi/yt-dlp-web-ui:latest`.
When I'm home i'll issue a new release on the :latest tag.

**Comment by Jmmx1237** [comment]
> at the moment try the image `ghcr.io/marcopeocchi/yt-dlp-web-ui:master`. When I'm home i'll issue a new release on the :latest tag.

I will try this later, thank you.
