### ISSUE TITLE
Filfe path with Portainer

### ISSUE THREAD

**Issue by Jmmx1237** [marcopeocchi/yt-dlp-web-ui#40]
Hi,
how can I set the download path with portainer, if I give the command -v /home/user/downloads:/downloads or try to set the path by the volume option in portainer, it does not work. Need some help please.

I need to set the download path to a mounted network share, can this probably be simplified?

If I start it without portainer only with Docker and specify the path with -v /mnt/xyz:/usr/src/lp-w/downloads, then it works strangely. But how do I make it run with Portainer?

**Comment by CrazyWolf13** [comment]
> Hi,
> how can I set the download path with portainer, if I give the command -v /home/user/downloads:/downloads or try to set the path by the volume option in portainer, it does not work. Need some help please.
> 
> I need to set the download path to a mounted network share, can this probably be simplified?
> 
> If I start it without portainer only with Docker and specify the path with -v /mnt/xyz:/usr/src/lp-w/downloads, then it works strangely. But how do I make it run with Portainer?
> 

Hi 
For me it worked flawlessly, please reply to me if you still couldn't start it, then i'll send  you a guide.
