### ISSUE TITLE
Initial Download to Temporary Directory

### ISSUE THREAD

**Issue by kucksdorfs** [marcopeocchi/yt-dlp-web-ui#43]
I know this isn't the default functionality in yt-dlp or youtube-dl, but would it be possible to have the videos download to a temporary location and then move the download location once complete?

So when I click Start the download starts in /temp or something similar and then once the download is complete move to /download.

**Comment by mchangrh** [comment]
You can achieve this with `yt-dlp -P` or `--path` to specify a temp path
