### ISSUE TITLE
Download Live Stream Issue

### ISSUE THREAD

**Issue by Wado729** [marcopeocchi/yt-dlp-web-ui#47]
When trying to download a live stream i.e. chaturbate, the stream doesn't get downloaded.  The GUI immediate changes the progress bar to green and nothing is downloaded.  Also, the entry is blank in the GUI.

![image](https://user-images.githubusercontent.com/85810628/226707064-663f4fb7-bd29-4a0d-b854-33465a1df5e6.png)

**Comment by Wado729** [comment]
You can delete this, it was a configuration issue on my side.

**Comment by OneCreek** [comment]
@Wado729 how did you solve it - what configuration did you use?

**Comment by Wado729** [comment]
I had to reinstall openmediavault, somehow during the install I messed up something.
