### ISSUE TITLE
Download Path and more metadata

### ISSUE THREAD

**Issue by schmoaaaaah** [marcopeocchi/yt-dlp-web-ui#48]
Hi.

I was wondering if there is some sort of documentation about the rpc api.
I found a little information from your [other rpc project](https://github.com/marcopeocchi/yt-dlp-rpc) and the rpcclient.js, but maybe there is something a little more userfriendly and more complete?
Also would it be possible to add the path of the downloaded media to the rpc response or possibly even the whole yt-dlp metadata?

**Comment by Schmoaaaaah** [comment]
Hi.

That looks really good thank you. I agree with the bulkyness of the whole yt-dlp payload.
Maybe a extra function that just returns metadata of a video without downloading?
I added there example of how to do it. You probaply call the executable with parameters as you use go?
To do it with parameters would probaply be -j --no-download
```py
import json
import yt_dlp

URL = 'https://www.youtube.com/watch?v=BaW_jenozKc'

# ℹ️ See help(yt_dlp.YoutubeDL) for a list of available options and public functions
ydl_opts = {}
with yt_dlp.YoutubeDL(ydl_opts) as ydl:
    info = ydl.extract_info(URL, download=False)

    # ℹ️ ydl.sanitize_info makes the info json-serializable
    print(json.dumps(ydl.sanitize_info(info)))
```
