### ISSUE TITLE
Request for download link and option to delete downloaded video

### ISSUE THREAD

**Issue by Ammar7347** [marcopeocchi/yt-dlp-web-ui#50]
Firstly, I would like to appreciate your work as everything works flawlessly for me. However, I would like to ask if you could add an option to the WebUI to generate/show a download link so that the downloaded video/audio file can be exported/downloaded to any device using the browser. Currently, in order to download from my server, I have to use a FTP client.

Also, I would like to suggest a settings/button to delete the downloaded file from the server instead of manually deleting the downloaded files using CLI rm-rf or FTP client.

These aforementioned features can also be combined together e.g. auto delete downloaded fille from the server after I or a user successfully downloaded the file to a device using a browser or maybe after every x days it gets deleted.

**Comment by marcopeocchi** [comment]
On its way 😎 👍 

But atm I won't add the autodelete function since it can be easily implemented with a cronjob.
The files will be accessible through the web UI and served as partial content whenever possible.
