### ISSUE TITLE
(task list) show finished task

### ISSUE THREAD

**Issue by deluxghost** [marcopeocchi/yt-dlp-web-ui#6]
also show finished downloads, and a user can delete it from the list (but do not delete file), or download the file through the browser

**Comment by deluxghost** [comment]
to be clarified, I think I was talking about a download task list, just like any downloader apps

**Comment by CrazyWolf13** [comment]
> to be clarified, I think I was talking about a download task list, just like any downloader apps

Hi I think he is working on something like that check #10

**Comment by marcopeocchi** [comment]
closed by #59
