### ISSUE TITLE
Login Support

### ISSUE THREAD

**Issue by CDN18** [marcopeocchi/yt-dlp-web-ui#60]
I would like to deploy this project on the public network, but without login support, anyone with this URL can call the service to download videos. Is it possible to add login support?

**Comment by marcopeocchi** [comment]
ATM only the RPC side support authentication.

**Comment by arbdevml** [comment]
Login can be implemented by Authelia and Nginx reverses the proxy.

**Comment by CDN18** [comment]
> Login can be implemented by Authelia and Nginx as a reverse proxy.

I am currently using nginx basic auth as a temporary solution. It would be more convenient if the web-ui itself supports authentication though.

**Comment by marcopeocchi** [comment]
@CDN18 to be more clear, username and password authentication without RPC authentication?

if so, it can be done without heavy changes.

**Comment by marcopeocchi** [comment]
anyway followup is on #62

**Comment by CDN18** [comment]
> @CDN18 to be more clear, username and password authentication without RPC authentication?
> 
> 
> 
> if so, it can be done without heavy changes.

@marcopeocchi Yes, that's exactly what I think.

**Comment by marcopeocchi** [comment]
closed as login by username and password is already implemented
