### ISSUE TITLE
Mobile Access

### ISSUE THREAD

**Issue by eximo84** [marcopeocchi/yt-dlp-web-ui#64]
When I browse to the web site in a mobile browser I get a greyed out page with a blue loading circle and it never goes away. 

Website works fine on desktop (edge)

I'm using iOS 17 beta 3 with mobile safari.

**Comment by marcopeocchi** [comment]
Unfortunately I cannot replicate the issue. Safari desktop works fine though. Anyway a screenshot would be useful, thanks :)

**Comment by eximo84** [comment]
![image](https://github.com/marcopeocchi/yt-dlp-web-ui/assets/25502878/288b2dec-fd80-4619-9cf7-7e5163ba4f6e)

This is what I get. Let me check from a non iOS 17 beta device.

**Comment by kabegithub** [comment]
> ![image](https://user-images.githubusercontent.com/25502878/253627592-288b2dec-fd80-4619-9cf7-7e5163ba4f6e.png)
> 
> This is what I get. Let me check from a non iOS 17 beta device.

Same for me. iOS 15.3.1 safari iPhone SE 2020

**Comment by mrkrisutley** [comment]
Yeah, IDK if you can add a lightweight page that will work for mobile phones.  I get the same as the users above from my iPhone.  I don't even need all the options pages, just a simple HTML page to put the link in would be great!

**Comment by mrkrisutley** [comment]
Just figured out if I run it with -p 80:3033 instead of -p3033:3033 it will load on the iPhone by just using the ip address.
192.168.1.1 instead of 192.168.1.1:3033.

**Comment by marcopeocchi** [comment]
@mrkrisutley maybe yes, it's too much bloated for mobile. I could add a simple non interactive HTML page but I'm worried that's something about iphones (maybe the connection isn't secure and it can't connect to the rpc interface via **fetch**).
The solution might be a form based input, but I have to test it.

**Comment by mrkrisutley** [comment]
So I did figure out if I disable my wireless and connect back to my VPN, the page loads.
