### ISSUE TITLE
Output Arg

### ISSUE THREAD

**Issue by eximo84** [marcopeocchi/yt-dlp-web-ui#65]
So I'm trying to integrate this with Jellyfin using this add on:

https://github.com/ankenyr/jellyfin-youtube-metadata-plugin

The add on requires a specific file name

3Blue1Brown - 20211023 - A_few_of_the_best_math_explainers_from_this_summer [F3Qixy-r_rQ].mkv

I'm trying to use the following arg

--output "%(uploader)s/%(uploader)s - %(upload_date)s - %(title)s/%(uploader)s - %(upload_date)s - %(title)s [%(id)s].%(ext)s"

However nothing is downloaded when I use this --output arg.

**Comment by marcopeocchi** [comment]
@eximo84 try enabling the "file name overriding" option, then paste your template.

![image](https://github.com/marcopeocchi/yt-dlp-web-ui/assets/35533749/47b87e63-c62d-4b12-87ca-b6cdc39073d1)

**Comment by eximo84** [comment]
Ah ok. Done that and without using the -o switch and "" the template is accepted and works as expected. 

Thanks

Can close.
