### ISSUE TITLE
Feature Request: Expose config folder or file on Docker for persistent changes.

### ISSUE THREAD

**Issue by 2IkHLHB** [marcopeocchi/yt-dlp-web-ui#66]
According to the provided instructions on this project's GitHub page, by running yt-dlp-webui in standalone mode we, as the users, have the ability to also specify a config file. It would be nice to have the same option under Docker, by exposing the config folder outside the Docker image, like so many projects allow the users to do.

**Comment by marcopeocchi** [comment]
Ok @2IkHLHB I'm on it :)
