### ISSUE TITLE
Is it possible to pass custom options to yt-dlp via settings?

### ISSUE THREAD

**Issue by wy580477** [marcopeocchi/yt-dlp-web-ui#7]
Your awesome project looks more advanced than other yt-dlp web frontends. 

There is one missing feature which prevents me from switch over, settings.json only has download_path option.

Is there any way to pass additional options to yt-dlp?

**Comment by marcopeocchi** [comment]
Hello! If you mean cli arguments to yt-dlp, yes it's totally doable. I will provide a way to do that.

**Comment by wy580477** [comment]
> Hello! If you mean cli arguments to yt-dlp, yes it's totally doable. I will provide a way to do that.

Yeah, cli arguments would be awesome. The WebUI which I'm using only support json format arguments, it‘s a pain in ass to dig around source code to find out json options.

**Comment by marcopeocchi** [comment]
![image](https://user-images.githubusercontent.com/35533749/171993403-79fa4d59-f030-4082-9030-d85c8f95ea46.png)

Would a format like this be sufficient?

Each array entry is effectively a yt-dlp cli argument

**Comment by wy580477** [comment]
Would multiple profiles be hard to implement? If profiles can be switched via WebUI, this would be a very flexible way to extend WebUI functions. 

```
{
    "profile": [
        {
            "tag": "profile_mp4",
            "download_path": "/data1",
            "cliArgs": [
                "-f mp4",
                "--exec script.sh"
            ]
        },
        {
            "tag": "profile_mkv",
            "download_path": "/data2",
            "cliArgs": [
                "-f mkv",
                "--exec script2.sh"
            ]
        }
    ]
}
```

**Comment by marcopeocchi** [comment]
I understand the idea but I think it's a little bit out of scope.
It will surely applicable in a context where there's multiple separate yt-dlp instances but this is not the case (or at least not what I've designed at the beginning)

**Comment by wy580477** [comment]
Thx.
