### ISSUE TITLE
API

### ISSUE THREAD

**Issue by MortRainey** [marcopeocchi/yt-dlp-web-ui#70]
Hi,

is there some kind of API to send Links to the UI? I would like to build an iOS shortcut to add a download. 

greetings 
waldi

**Comment by marcopeocchi** [comment]
Hello @MortRainey!

ATM it's exposed a JSON-RPC interface only. I'll happly implement some REST endpoints though.
Which kind of functionalities should the API expose (beside the RPC ones)?

**Comment by MortRainey** [comment]
Wow trank you. 🙂
