### ISSUE TITLE
Folder on playlist download

### ISSUE THREAD

**Issue by CrazyWolf13** [marcopeocchi/yt-dlp-web-ui#75]
Is it possible to let yt-dlp create a folder on playlist download, so the download folder does not get messy.

Could be done with a simple -o '/%%(playlist_title)s/%%(title)s.%%(ext)s'

**Comment by marcopeocchi** [comment]
it's preferences, you can pass your template to the "custom file name" option.

**Comment by CrazyWolf13** [comment]
> it's preferences, you can pass your template to the "custom file name" option.

Sorry, can you explain a bit more?

I currently have mappen the config folder but there is no file, should I create the config manually?

And what should I write in the config to get the expected results with the string above?

https://github.com/marcopeocchi/yt-dlp-web-ui#config-file
Have found this but there is no option to set some sort of yt-dlp output flag
