### ISSUE TITLE
[Problematic] Playlist only downloading 1 or 2 videos

### ISSUE THREAD

**Issue by CrazyWolf13** [marcopeocchi/yt-dlp-web-ui#77]
I started a playlist download but it downloads only 2 things and the others stay on "Pending"
I don't really know what else to write here, as I couldn't find a log.

**Comment by CrazyWolf13** [comment]
Sometimes there doesn't even happen anything at all, I start the download and then just nothing happens.

**Comment by marcopeocchi** [comment]
All of this when "playlist support" is checked? Or it's a general behavior?

**Comment by CrazyWolf13** [comment]
> All of this when "playlist support" is checked? Or it's a general behavior?

Yes only when playlist is checked

**Comment by marcopeocchi** [comment]
@CrazyWolf13 ok i'll look into that

**Comment by CrazyWolf13** [comment]
Hi
I saw you updating and I think it seems more stable of what I can tell by the few test I run, however that could also be just luck;)

But one thing I noticed, what about format selection, if I check it in settings there are just no downloads at all

**Comment by mbedez** [comment]
Hi
Same problem here!

**Comment by marcopeocchi** [comment]
@mbedez @CrazyWolf13, which value your download queue size are set at? how many cores the machine running yt-dlp-webui has?

I found out that a queue size of 2 causes this problems, setting it at 1 or more than 2 solves the issue in my case.

**Comment by CrazyWolf13** [comment]
> @mbedez @CrazyWolf13, which value your download queue size are set at? how many cores the machine running yt-dlp-webui has?
> 
> I found out that a queue size of 2 causes this problems, setting it at 1 or more than 2 solves the issue in my case.

I did not specify it anywhere. Is that neccessary?
