### ISSUE TITLE
404 when the application put under nginx subdirectory with proxy_pass

### ISSUE THREAD

**Issue by chaoqing** [marcopeocchi/yt-dlp-web-ui#78]
I tried to put the application under nginx subdirectory with `proxy_pass` like following:

```
location ~/yt-dlp/(.*)$ {
	    proxy_pass http://127.0.0.1:3033/$1;
	    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	    proxy_set_header Host $http_host;
	    proxy_redirect off;

		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";

	    client_max_body_size 20000m;
	    proxy_connect_timeout       3000;
	    proxy_send_timeout          3000;
	    proxy_read_timeout          3000;
	    send_timeout                 @3000;
	}
```

It will not work because the whole front end use absolute assets address, even after following fix there will still be application internal error.

[Patch](https://github.com/chaoqing/yt-dlp-web-ui/blob/c78651c5825a93d94858b319d45af62bde13898e/frontend/vite.config.ts#L8) 

Could you help fix this issue?

**Comment by NicksQ69** [comment]
+1
I'd also like the reverse proxy to work, so I can have several of my applications on the same machine.

**Comment by marcopeocchi** [comment]
Apologies for the late response. I'm gonna fix this by tomorrow. 😎 
@chaoqing could you post a screenshot with the error?

**Comment by chaoqing** [comment]
To reproduce the error, try clone the codebase and build the frontend, then try only serve `dist` with `python -m http.server`.
 
Notice I made one line change to `vite.config.ts` and serve under `frontend` folder,

```
➜ /tmp/yt-dlp-web-ui/frontend (13dd952) $ git status
HEAD detached at v3.0.0
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   vite.config.ts

no changes added to commit (use "git add" and/or "git commit -a")
 ➜ /tmp/yt-dlp-web-ui/frontend (13dd952) $ git diff
diff --git a/frontend/vite.config.ts b/frontend/vite.config.ts
index fb6b74a..dfca237 100644
--- a/frontend/vite.config.ts
+++ b/frontend/vite.config.ts
@@ -5,6 +5,7 @@ import { resolve } from 'path';
 
 export default defineConfig(() => {
     return {
+           base: './',
         plugins: [
             react(),
             ViteYaml(),
➜ /tmp/yt-dlp-web-ui/frontend (13dd952) $ python3 -m http.server
Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...
127.0.0.1 - - [21/Aug/2023 05:01:56] "GET /dist/ HTTP/1.1" 304 -
127.0.0.1 - - [21/Aug/2023 05:01:56] "GET /dist/assets/index-aaff9234.js HTTP/1.1" 304 -
```

Following is the screenshot of error, 
<img width="978" alt="404" src="https://github.com/marcopeocchi/yt-dlp-web-ui/assets/2959260/53ba2a3e-b2c6-4244-9789-24aae6ae224c">

I am not sure why 404 happened while no such network error found in the Chrome debugger panel.

**Comment by marcopeocchi** [comment]
Using this **nginx.conf** which is identical to @chaoqing one and using an hash router it works.

```
worker_processes  8;

events {
    worker_connections  1024;
}

http {
    include       mime.types;

    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    gzip  on;

    server {
        listen       80;
        server_name  localhost;

        location ~/yt-dlp/(.*)$ {
            proxy_pass http://127.0.0.1:3033/$1;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            client_max_body_size    20000m;
            proxy_connect_timeout   3000;
            proxy_send_timeout      3000;
            proxy_read_timeout      3000;
            send_timeout            3000;
        }
    }
 }
```

The problem as mentioned is that vite bundle everything with absolute paths, setting `base: ''` bundles with paths relative to `./`. An hash router is better suited for a SPA like this.

#### Regarding the base path variable
It's not really necessary, I've added a setting which enables the use of the RPC in conjunction with a reverse proxy.

**At the first boot behind the reverse proxy**  

![Screenshot_20230821_114343](https://github.com/marcopeocchi/yt-dlp-web-ui/assets/35533749/39fb0622-66f2-4c52-9c9a-2114f0a945f5)

**Then set the address accordingly to the reverse proxy subfolder**   

![Screenshot_20230821_120247](https://github.com/marcopeocchi/yt-dlp-web-ui/assets/35533749/9f2fe509-9504-4e71-a3ea-603be82c5dc1)

Everything works just fine :sunglasses:   

![image](https://github.com/marcopeocchi/yt-dlp-web-ui/assets/35533749/3857964a-1e2d-4968-9dec-d267c8a91966)
