### ISSUE TITLE
download path error

### ISSUE THREAD

**Issue by brixxnatt** [marcopeocchi/yt-dlp-web-ui#85]
PLease how to change download path in details , also please can you do the username and password login , and really thank you for this script , amazing work

**Comment by marcopeocchi** [comment]
Hello!

In order to change the download path you must enable the **Enable output path overriding** option in the settings page.
Another way is to enable **Enable custom yt-dlp args** (again in the settings page) and pass `-o your_absolute_path`

Login support with username and password will be merged after i close this issue 🤠

**Comment by brixxnatt** [comment]
I have no idea how to do that  ,  i am running it on docker , and i need to make the path fixed all the time via a config file , when i run this  
docker run -d --name=yt-dlp-webui --restart unless-stopped -p 3033:3033 -v /var/lib/output/:/var/lib/output/ marcobaobao/yt-dlp-webui:latest

I cant find the files in this folder , also in the page it still says /downloads

**Comment by marcopeocchi** [comment]
Assuming your container can access `/var/lib/output`, there's one thing you can do.
Use this docker run script:
```sh
docker run -d \
  --name=yt-dlp-webui \
  --restart unless-stopped \
  -p 3033:3033 \
  -v /var/lib/output:/var/lib/output
  -v /path/for/config:/config
  marcobaobao/yt-dlp-webui:latest
```
Inside `/path/for/config` create `config.yml`.

Inside `config.yml`
```yaml
# Downloads settings
downloadPath: /downloads
```

Even if with docker it shouldn't be necessary.
My guess is that `/var/lib/output` isn't accessible by your container.

**Comment by marcopeocchi** [comment]
Anyway if you want to hop on discord i will try to guide you from there.
https://discord.gg/MszUhRVkF
