### ISSUE TITLE
ability to change yt-dlp WebUI page title

### ISSUE THREAD

**Issue by brixxnatt** [marcopeocchi/yt-dlp-web-ui#86]
please ability to change "yt-dlp WebUI"page title

**Comment by marcopeocchi** [comment]
A solution like this is sufficient?
![image](https://github.com/marcopeocchi/yt-dlp-web-ui/assets/35533749/46155468-0960-4fa4-9b79-b6e29229b9cf)
![image](https://github.com/marcopeocchi/yt-dlp-web-ui/assets/35533749/55cbc58d-1c0a-4e6a-a507-1089bdd852ab)

**Comment by brixxnatt** [comment]
yes thankssss
