### ISSUE TITLE
Need more settings available

### ISSUE THREAD

**Issue by archtaurus** [marcopeocchi/yt-dlp-web-ui#9]
Hope more yt-dlp configs can be setup in this app, thanks:)
Such as output combine format to .mkv

**Comment by michelebossa** [comment]
Hello i need to have the adding into path of channel name to diversificate the download ;)

**Comment by marcopeocchi** [comment]
@archtaurus with the latest release you can pass arbitrary arguments to yt-dlp. 
A new option in the settings page allows you to enable that.

By params i mean [these](https://github.com/yt-dlp/yt-dlp#usage-and-options).

**Comment by marcopeocchi** [comment]
@michelebossa could you provide a practical example?
If you need to override the output filename or path you can do that.
In the settings page enable both filaname and path override options, then provide the name/path you want to change per download.

**Comment by michelebossa** [comment]
Hi i'd like to write the file not all in the same folder but in a folder with channel name i suppose it is the option %(uploader).

I have no option i assume i'm using the master image of docker and not contain the your last addition 
<img width="744" alt="image" src="https://user-images.githubusercontent.com/38975058/212296028-d2e0a5c1-8db8-4b8d-88a9-b4cfe374d676.png">

how i can update my docker compose file?

**Comment by marcopeocchi** [comment]
I've updated the Dockerfile.
Btw now the latest container image is under the `latest` tag.
```
docker pull ghcr.io/marcopeocchi/yt-dlp-web-ui:latest
```
I've created a new CI/CD action, if you're using the ghcr image wait for the action to complete.

Let me know if the setting appear.

**Comment by michelebossa** [comment]
I have updated the image and it is working but i neeed to fill every time the customizing there is a way to have always the new filename rules?
<img width="392" alt="image" src="https://user-images.githubusercontent.com/38975058/212364563-94405167-5aab-4561-9e66-471e35523c32.png">

Ps the port it is changed to 3033 but readme see 3022 maybe can help if fixed into readme page

<img width="516" alt="image" src="https://user-images.githubusercontent.com/38975058/212365234-7229eeee-1519-45cd-a163-86fc55baaf5d.png">

Thanks

**Comment by marcopeocchi** [comment]
I've just issued a [new release](https://github.com/marcopeocchi/yt-dlp-web-ui/actions/runs/3913181723) containing the fixes.

**Comment by michelebossa** [comment]
Build finished but my dockercompose didn't find new version
<img width="173" alt="image" src="https://user-images.githubusercontent.com/38975058/212377610-2ad38c38-5b61-4af4-b779-3e7d3d3182e9.png">

<img width="329" alt="image" src="https://user-images.githubusercontent.com/38975058/212377695-5047f745-d200-42d2-92bd-a4bf5dabb97a.png">

I need to wait more time?

**Comment by marcopeocchi** [comment]
if a `docker-compose pull` doesn't help I will wait just a bit more.

**Comment by michelebossa** [comment]
i see the field it is autofilled
<img width="650" alt="image" src="https://user-images.githubusercontent.com/38975058/212389023-0e3a79bc-e9e3-42b5-a3e2-a46aff005208.png">

but it is a session data stored i think i need to set in each device 👍

**Comment by marcopeocchi** [comment]
yes it's saved in localstorage and so persisted in a single device.
