### ISSUE TITLE
Informations

### ISSUE THREAD

**Issue by CrazyWolf13** [marcopeocchi/yt-dlp-web-ui#94]
Hi
I really like this Project and since a long time I wanted to build the same for the software streamlink (yt-dlp but twitch)

Now as I'm quite new to programming and currently starting in IT, could you give me some advice how I could get started here?

My Website Layout is mostly designed and I also have already begun writing html.
But the part with running the command and extracting progress really gives me headaches.

**Comment by marcopeocchi** [comment]
Sure, maybe let's discuss it on discord https://discord.gg/WP3KSzTR
