### ISSUE TITLE
Custom arguments broken

### ISSUE THREAD

**Issue by dot-mike** [marcopeocchi/yt-dlp-web-ui#97]
When using custom arguments for YT-DLP the program does not download / save the video file.

**Reproduce**
1. Enable the following options in settings
- Enable output file name overriding
- Enable custom yt-dlp args (great power = great responsabilities)
2. Navigate to download video
3. Set download video to `https://www.youtube.com/@jawed/videos` and use the following options:
- YT-dlp arguments: `-f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio' --merge-output-format mp4`
- custom filename: `%(uploader)s_%(channel_id)s/%(title)s [%(id)s].%(ext)s`

**What occurred**
I can see that the process is yt-dlp started in container by executing `ps | cat`, but video file is never downloaded to `/downloads` directory.

**What to expect**
File is present in `/downloads` directory

**Comments**
It works if I execute the same yt-dlp  command taken from running the command `ps | cat`.

**Logs , screenshot, etc**
```
2023/10/14 01:32:40 "POST http://192.168.10.90:3033/rpc/http HTTP/1.1" from 172.17.0.1:33052 - 200 74B in 322.692µs
2023/10/14 01:32:40  Metadata   49fc824a  https://www.youtube.com/@jawed/videos
2023/10/14 01:32:46  FINISH   49fc824a  https://www.youtube.com/@jawed/videos
2023/10/14 01:33:33  Successfully serialized session
```

**Comment by marcopeocchi** [comment]
`'bestvideo+bestaudio'` is by default what yt-dlp uses. But I get what you mean, it's quite curious. I'll look into that.
